export const editorialSections = [
    {
      title: "Cultura",
      items: [
        {
          title: "Bolsonaro sobre tornozeleira eletrônica: 'Nunca pensei em sair do Brasil'",
          category: "Política",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Ex-presidente fala sobre investigações e futuro político",
          category: "Política",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Mais uma notícia política importante",
          category: "Política",
          time: "4 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Esportes",
      items: [
        {
          title: "Jogador se lesiona em treino e desfalca o time",
          category: "Esporte",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Final do campeonato será antecipada",
          category: "Esporte",
          time: "30 minutos atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Nova promessa do futebol brasileiro se destaca",
          category: "Esporte",
          time: "agora mesmo",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Economia",
      items: [
        {
          title: "Inflação tem leve alta em julho, aponta IBGE",
          category: "Economia",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Dólar fecha em queda após fala do presidente do Fed",
          category: "Economia",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Novo salário mínimo entra em vigor a partir de agosto",
          category: "Economia",
          time: "4 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Tecnologia",
      items: [
        {
          title: "Apple anuncia novo iPhone com IA integrada",
          category: "Tecnologia",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Hackers invadem sistema de transporte público",
          category: "Tecnologia",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Startup brasileira recebe aporte milionário",
          category: "Tecnologia",
          time: "5 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Saúde",
      items: [
        {
          title: "Nova vacina contra dengue será distribuída em setembro",
          category: "Saúde",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Campanha de vacinação contra gripe é prorrogada",
          category: "Saúde",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Pesquisa aponta aumento de casos de ansiedade no Brasil",
          category: "Saúde",
          time: "5 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Mundo",
      items: [
        {
          title: "Eleições nos EUA devem ter recorde de votos por correio",
          category: "Mundo",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Tensões aumentam entre países do leste europeu",
          category: "Mundo",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "ONU alerta para crise humanitária em região africana",
          category: "Mundo",
          time: "4 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Ciência",
      items: [
        {
          title: "Pesquisadores brasileiros descobrem nova espécie marinha",
          category: "Ciência",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Missão espacial da NASA encontra sinais de água em lua de Júpiter",
          category: "Ciência",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Novo estudo investiga efeitos do sono na memória",
          category: "Ciência",
          time: "5 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Entretenimento",
      items: [
        {
          title: "Novo filme da Marvel bate recorde de bilheteria",
          category: "Entretenimento",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Cantora pop anuncia turnê no Brasil",
          category: "Entretenimento",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Festival de música reúne milhares de pessoas no RJ",
          category: "Entretenimento",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Meio Ambiente",
      items: [
        {
          title: "Desmatamento na Amazônia cai 20% em um ano",
          category: "Meio Ambiente",
          time: "1 hora atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Nova lei visa proteger áreas costeiras",
          category: "Meio Ambiente",
          time: "3 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Cidades brasileiras sofrem com onda de calor intensa",
          category: "Meio Ambiente",
          time: "4 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
    {
      title: "Educação",
      items: [
        {
          title: "Novo Enem terá questões sobre inteligência artificial",
          category: "Educação",
          time: "2 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Universidades públicas ampliam cotas raciais",
          category: "Educação",
          time: "4 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
        {
          title: "Professores fazem paralisação nacional por reajuste",
          category: "Educação",
          time: "5 horas atrás",
          image: "/placeholder.svg?height=300&width=300",
        },
      ],
    },
  ];
  

 export const industriesData = [
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "Metalúrgica São Paulo Ltda",
      cnpj: "12.345.678/0001-90",
      address: "Rua Industrial, 1234",
      city: "São Paulo",
      state: "SP",
      sector: "Metalurgia",
      phone: "(11) 3456-7890",
      email: "contato@metalurgicasp.com.br",
      website: "https://metalurgicasp.com.br",
      employees: "500-1000",
      founded: "1985",
      rating: 4.8,
      description: "Especializada em fundição e usinagem de peças metálicas para diversos setores industriais.",
      specialties: ["Fundição", "Usinagem", "Soldas Especiais", "Tratamento Térmico"],
    },
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "Química Industrial Brasil S.A.",
      cnpj: "23.456.789/0001-01",
      address: "Av. das Indústrias, 5678",
      city: "Campinas",
      state: "SP",
      sector: "Química",
      phone: "(19) 2345-6789",
      email: "vendas@quimicabrasil.com.br",
      website: "https://quimicabrasil.com.br",
      employees: "1000+",
      founded: "1978",
      rating: 4.6,
      description: "Produção de produtos químicos industriais e soluções para diversos segmentos.",
      specialties: ["Produtos Químicos", "Solventes", "Aditivos", "Catalisadores"],
    },
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "AutoPeças Premium Ltda",
      cnpj: "34.567.890/0001-12",
      address: "Rua dos Mecânicos, 999",
      city: "São Bernardo do Campo",
      state: "SP",
      sector: "Automotivo",
      phone: "(11) 4567-8901",
      email: "comercial@autopecaspremium.com.br",
      website: "https://autopecaspremium.com.br",
      employees: "200-500",
      founded: "1992",
      rating: 4.4,
      description: "Fabricação de componentes automotivos de alta qualidade para montadoras nacionais.",
      specialties: ["Componentes Automotivos", "Injeção Plástica", "Estamparia", "Montagem"],
    },
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "Têxtil Moderna Indústria",
      cnpj: "45.678.901/0001-23",
      address: "Distrito Industrial, 2468",
      city: "Americana",
      state: "SP",
      sector: "Têxtil",
      phone: "(19) 3456-7890",
      email: "info@textilmoderna.com.br",
      website: "https://textilmoderna.com.br",
      employees: "300-500",
      founded: "1965",
      rating: 4.2,
      description: "Produção de tecidos técnicos e industriais para diversos segmentos do mercado.",
      specialties: ["Tecidos Técnicos", "Não Tecidos", "Fibras Sintéticas", "Acabamentos"],
    },
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "Alimentos Naturais do Brasil",
      cnpj: "56.789.012/0001-34",
      address: "Fazenda Industrial, Km 45",
      city: "Ribeirão Preto",
      state: "SP",
      sector: "Alimentício",
      phone: "(16) 2345-6789",
      email: "contato@alimentosnaturais.com.br",
      website: "https://alimentosnaturais.com.br",
      employees: "800-1000",
      founded: "1988",
      rating: 4.7,
      description: "Processamento e distribuição de alimentos naturais e orgânicos certificados.",
      specialties: ["Alimentos Orgânicos", "Processamento", "Embalagem", "Distribuição"],
    },
    {
      logo: "/placeholder.svg?height=64&width=64",
      name: "Construção Pesada Engenharia",
      cnpj: "67.890.123/0001-45",
      address: "Setor Industrial Norte, 1357",
      city: "Guarulhos",
      state: "SP",
      sector: "Construção",
      phone: "(11) 5678-9012",
      email: "projetos@construcaopesada.com.br",
      website: "https://construcaopesada.com.br",
      employees: "1000+",
      founded: "1975",
      rating: 4.5,
      description: "Especializada em grandes obras de infraestrutura e construção industrial.",
      specialties: ["Infraestrutura", "Construção Industrial", "Projetos Especiais", "Engenharia"],
    },
  ]